# --- Physics Constants (PDG) ---
pdg:
  br_b_to_jpsik:    {value: 1.020e-3, error: 0.019e-3}
  br_b_to_psi2sk:   {value: 6.24e-4,  error: 0.21e-4}
  br_jpsi_to_mumu:  {value: 5.961e-2, error: 0.03e-2}
  br_psi2s_to_mumu: {value: 8.0e-3,   error: 0.6e-3}
  br_jpsi_to_ee:    {value: 5.971e-2, error: 0.032e-2}
  br_psi2s_to_ee:   {value: 7.94e-3,  error: 0.22e-3}

# --- Analysis Data ---
channels:
  mumu:
    2018:
      lumi: {value: 33.6, error: 0.84} 
      yields:
        n_jpsi: {value: 728000, error: 1000}
        n_psi2s: {value: 68300, error: 500}
      effs:
        eff_jpsi: {value: 9.31e-4, error: 4e-6}
        eff_psi2s: {value: 1.112e-3, error: 4e-6}
    2022:
      lumi: {value: 34.7486, error: 0.87}
      yields:
        n_jpsi: {value: 3921547, error: 1641}
        n_psi2s: {value: 376367, error: 611}
      effs:
        eff_jpsi: {value: 0.00453, error: 0.00001}
        eff_psi2s: {value: 0.00520, error: 0.00001}
  ee:
    2022:
      lumi: {value: 18.1796, error: 0.45}
      yields:
        n_jpsi: {value: 15897.61, error: 152.29}
        n_psi2s: {value: 1126.6, error: 37.72}
      effs:
        eff_jpsi: {value: 1.41e-4, error: 4.7e-5}
        eff_psi2s: {value: 1.24e-4, error: 4.3e-5}
